### ISSUE TITLE
SOLVED (MusclePr is a legend) - Are there any legends willing to update this?

### ISSUE THREAD

**Issue by XavierBit** [vladmarica/better-ping-display-fabric#57]
Hi!
It seems the last dependency patch for Better Ping Display doesn't work for 1.21.9 / 10 and I couldn't get it to run by just changing the Minecraft version in fabric_loader_dependencies.json.

Who's the legend taking this on? Thanks!

**Comment by davepusey** [comment]
Version 1.1.1 from Modrinth works in 1.21.10

Please can the version tags on modrinth be updated so that it shows in the search in Prism.

**Comment by davepusey** [comment]
Make sure you are using Fabric Loader 0.17.2 and the latest Fabric API

**Comment by MusclePr** [comment]
#55

**Comment by XavierBit** [comment]
> Version 1.1.1 from Modrinth works in 1.21.10
> 
> Please can the version tags on modrinth be updated so that it shows in the search in Prism.

No, it doesn't for me, using the last version available on Modrinth. 
If I use Fabric loader 0.17.3 it says that Better Ping Display isn't compatible with Minecraft:

<img width="796" height="484" alt="Image" src="https://github.com/user-attachments/assets/eaa654ca-b9ac-4b28-8d6a-7a9fcade5348" />

If I change Fabric loader to 0.17.2 it still complains, even asking for the 0.17.3 loader:

<img width="796" height="485" alt="Image" src="https://github.com/user-attachments/assets/7de4022e-b187-40ec-b213-c70bd5da1a76" />

**Comment by XavierBit** [comment]
> [#55](https://github.com/vladmarica/better-ping-display-fabric/pull/55)

This worked, you are a legend!

**Comment by davepusey** [comment]
> > Version 1.1.1 from Modrinth works in 1.21.10
> > Please can the version tags on modrinth be updated so that it shows in the search in Prism.
> 
> No, it doesn't for me, using the last version available on Modrinth. If I use Fabric loader 0.17.3 it says that Better Ping Display isn't compatible with Minecraft:

Well it does for me...

<img width="854" height="253" alt="Image" src="https://github.com/user-attachments/assets/d2e69ae7-a568-42ea-bd9d-bc8490a00d48" />

**Comment by MusclePr** [comment]
@XavierBit 
By placing this [fabric_loader_dependencies.json](https://github.com/user-attachments/files/23010962/fabric_loader_dependencies.json) file in the `config/` folder, it will override the dependency even in 1.1.1 and avoid the startup error.

@davepusey 
Have you tried pressing the TAB key?

**Comment by davepusey** [comment]
Yes... it works as expected...

<img width="854" height="480" alt="Image" src="https://github.com/user-attachments/assets/299e5cfe-e83c-4035-a44d-1ac42fdca11e" />

**Comment by litekin** [comment]
Can someone fork and maintain this on Modrinth as well? I want to include it in my modpack :)

**Comment by MusclePr** [comment]
@davepusey 
In my environment, it crashes, so could you try turning off other mods?
<details><summary>crash-log</summary>

```log
Description: Unexpected error

java.lang.NoSuchMethodError: 'int net.minecraft.class_332.method_25303(net.minecraft.class_327, java.lang.String, int, int, int)'
	at knot//com.vladmarica.betterpingdisplay.hud.CustomPlayerListHud.renderPingDisplay(CustomPlayerListHud.java:32)
	at knot//net.minecraft.class_355.redirect$zza000$betterpingdisplay$redirectRenderLatencyIconCall(class_355.java:1049)
	at knot//net.minecraft.class_355.method_1919(class_355.java:247)
	at knot//net.minecraft.class_329.method_55804(class_329.java:444)
	at knot//net.minecraft.class_329.mixinextras$bridge$method_55804$159(class_329.java)
	at knot//net.minecraft.class_329.md701328$fabric-rendering-v1$lambda$wrapPlayerList$21$1(class_329.java:2175)
	at knot//net.fabricmc.fabric.impl.client.rendering.hud.HudElementRegistryImpl$RootLayer.render(HudElementRegistryImpl.java:216)
	at knot//net.minecraft.class_329.wrapOperation$znb000$fabric-rendering-v1$wrapPlayerList(class_329.java:2175)
	at knot//net.minecraft.class_329.method_1753(class_329.java:241)
	at knot//net.minecraft.class_757.method_3192(class_757.java:564)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1380)
	at knot//net.minecraft.class_310.method_1514(class_310.java:969)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.modrinth.theseus.MinecraftLaunch.relaunch(MinecraftLaunch.java:63)
	at com.modrinth.theseus.MinecraftLaunch.main(MinecraftLaunch.java:28)
```
</details>

**Comment by davepusey** [comment]
Yep, still works...

```
[11:43:10] [main/INFO]: Loading Minecraft 1.21.10 with Fabric Loader 0.17.2
[11:43:10] [main/INFO]: Loading 51 mods:
	- betterpingdisplay 1.1.1
	- fabric-api 0.136.0+1.21.10
	   |-- fabric-api-base 1.0.0+14b92d896f
	   |-- fabric-api-lookup-api-v1 1.6.106+d17682156f
	   |-- fabric-biome-api-v1 16.1.0+c2417d4f6f
	   |-- fabric-block-api-v1 1.1.5+d17682156f
	   |-- fabric-block-view-api-v2 1.0.34+e4fd1b926f
	   |-- fabric-command-api-v2 2.4.0+c0ab2d5d6f
	   |-- fabric-content-registries-v0 10.2.4+b6a242646f
	   |-- fabric-convention-tags-v1 2.1.48+7f945d5b6f
	   |-- fabric-convention-tags-v2 2.16.0+552403eb6f
	   |-- fabric-crash-report-info-v1 0.3.18+33df5e6e6f
	   |-- fabric-data-attachment-api-v1 1.8.30+68e881bd6f
	   |-- fabric-data-generation-api-v1 23.2.24+d8b85ef16f
	   |-- fabric-dimensions-v1 4.0.22+38b9cc196f
	   |-- fabric-entity-events-v1 2.1.13+fde3702c6f
	   |-- fabric-events-interaction-v0 4.0.36+5ba217126f
	   |-- fabric-game-rule-api-v1 1.1.1+e47eaae56f
	   |-- fabric-item-api-v1 11.5.9+9bce411b6f
	   |-- fabric-item-group-api-v1 4.2.25+86b3ae576f
	   |-- fabric-key-binding-api-v1 1.1.1+b3ba9c486f
	   |-- fabric-lifecycle-events-v1 2.6.9+33df5e6e6f
	   |-- fabric-loot-api-v2 3.0.65+3f89f5a56f
	   |-- fabric-loot-api-v3 2.0.12+d17682156f
	   |-- fabric-message-api-v1 6.1.7+3154c1c86f
	   |-- fabric-model-loading-api-v1 6.0.2+3ffd6ef06f
	   |-- fabric-networking-api-v1 5.1.0+b095d8db6f
	   |-- fabric-object-builder-api-v1 21.1.26+9bce411b6f
	   |-- fabric-particles-v1 4.2.3+a0ee59a46f
	   |-- fabric-recipe-api-v1 8.1.27+d17682156f
	   |-- fabric-registry-sync-v0 6.1.42+679c8c5c6f
	   |-- fabric-renderer-api-v1 7.2.0+3706cdf36f
	   |-- fabric-renderer-indigo 4.1.1+d7df91576f
	   |-- fabric-rendering-fluids-v1 3.1.38+86b3ae576f
	   |-- fabric-rendering-v1 16.0.2+19a99b056f
	   |-- fabric-resource-conditions-api-v1 5.0.28+33df5e6e6f
	   |-- fabric-resource-loader-v0 3.2.3+3388a3b26f
	   |-- fabric-resource-loader-v1 1.0.3+8cc86c156f
	   |-- fabric-screen-api-v1 3.1.0+9c82a7986f
	   |-- fabric-screen-handler-api-v1 1.3.151+d17682156f
	   |-- fabric-serialization-api-v1 1.0.0+d857c9766f
	   |-- fabric-sound-api-v1 1.0.45+328a75ba6f
	   |-- fabric-tag-api-v1 1.2.11+2fa446b26f
	   |-- fabric-transfer-api-v1 6.0.15+79ec2c126f
	   \-- fabric-transitive-access-wideners-v1 6.5.3+41eb43436f
	- fabricloader 0.17.2
	   \-- mixinextras 0.5.0
	- java 21
	- minecraft 1.21.10
	- modmenu 16.0.0-rc.1
	   \-- placeholder-api 2.8.0+1.21.9
```

<img width="855" height="511" alt="Image" src="https://github.com/user-attachments/assets/8a8cb512-eb94-46c0-a891-c72de58b119c" />

**Comment by MusclePr** [comment]
@davepusey Thank you for your detail informations.
But it still crashes in my environment...

<details>
<summary>Crash-log</summary>

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2025-10-24 14:49:44
Description: Unexpected error

java.lang.NoSuchMethodError: 'int net.minecraft.class_332.method_25303(net.minecraft.class_327, java.lang.String, int, int, int)'
	at knot//com.vladmarica.betterpingdisplay.hud.CustomPlayerListHud.renderPingDisplay(CustomPlayerListHud.java:32)
	at knot//net.minecraft.class_355.redirect$zza000$betterpingdisplay$redirectRenderLatencyIconCall(class_355.java:1049)
	at knot//net.minecraft.class_355.method_1919(class_355.java:247)
	at knot//net.minecraft.class_329.method_55804(class_329.java:444)
	at knot//net.minecraft.class_329.mixinextras$bridge$method_55804$159(class_329.java)
	at knot//net.minecraft.class_329.md282596$fabric-rendering-v1$lambda$wrapPlayerList$21$1(class_329.java:2175)
	at knot//net.fabricmc.fabric.impl.client.rendering.hud.HudElementRegistryImpl$RootLayer.render(HudElementRegistryImpl.java:216)
	at knot//net.minecraft.class_329.wrapOperation$znb000$fabric-rendering-v1$wrapPlayerList(class_329.java:2175)
	at knot//net.minecraft.class_329.method_1753(class_329.java:241)
	at knot//net.minecraft.class_757.method_3192(class_757.java:564)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1380)
	at knot//net.minecraft.class_310.method_1514(class_310.java:969)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.modrinth.theseus.MinecraftLaunch.relaunch(MinecraftLaunch.java:63)
	at com.modrinth.theseus.MinecraftLaunch.main(MinecraftLaunch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at knot//com.vladmarica.betterpingdisplay.hud.CustomPlayerListHud.renderPingDisplay(CustomPlayerListHud.java:32)
	at knot//net.minecraft.class_355.redirect$zza000$betterpingdisplay$redirectRenderLatencyIconCall(class_355.java:1049)
	at knot//net.minecraft.class_355.method_1919(class_355.java:247)
	at knot//net.minecraft.class_329.method_55804(class_329.java:444)
	at knot//net.minecraft.class_329.mixinextras$bridge$method_55804$159(class_329.java)
	at knot//net.minecraft.class_329.md282596$fabric-rendering-v1$lambda$wrapPlayerList$21$1(class_329.java:2175)
	at knot//net.fabricmc.fabric.impl.client.rendering.hud.HudElementRegistryImpl$RootLayer.render(HudElementRegistryImpl.java:216)
	at knot//net.minecraft.class_329.wrapOperation$znb000$fabric-rendering-v1$wrapPlayerList(class_329.java:2175)
	at knot//net.minecraft.class_329.method_1753(class_329.java:241)

-- Uptime --
Details:
	JVM uptime: 23.706s
	Wall uptime: 16.754s
	High-res time: 15.916s
	Client ticks: 299 ticks / 14.950s
Stacktrace:
	at knot//net.minecraft.class_310.method_1587(class_310.java:2434)
	at knot//net.minecraft.class_310.method_54580(class_310.java:1038)
	at knot//net.minecraft.class_310.method_1514(class_310.java:993)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:506)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:72)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at com.modrinth.theseus.MinecraftLaunch.relaunch(MinecraftLaunch.java:63)
	at com.modrinth.theseus.MinecraftLaunch.main(MinecraftLaunch.java:28)

-- Affected level --
Details:
	All players: 1 total; class_746{name=Muscle_p, id=1734, pos=(-130.9165586876462, 119.0625, -494.9273298752407), mode=SURVIVAL, permission=4}
	Chunk stats: 1089, 295
	Level dimension: minecraft:hub-nimbarad
	Level spawn location: World: (-132,119,-487), Section: (at 12,7,9 in -9,7,-31; chunk contains blocks -144,-64,-496 to -129,319,-481), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 515729759 game time, 4073763 day time
	Server brand: Paper (Velocity)
	Server type: Non-integrated multiplayer server
	Tracked entity count: 428

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, betterpingdisplay, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-command-api-v2, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-resource-loader-v1, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-serialization-api-v1, fabric-sound-api-v1, fabric-tag-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, modmenu, placeholder-api

-- System Details --
Details:
	Minecraft Version: 1.21.10
	Minecraft Version ID: 1.21.10
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.8, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Azul Systems, Inc.
	Memory: 176391120 bytes (168 MiB) / 522190848 bytes (498 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 24
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) Ultra 9 285
	Identifier: Intel64 Family 6 Model 198 Stepping 2
	Microarchitecture: unknown
	Frequency (GHz): 2.50
	Number of physical packages: 1
	Number of physical CPUs: 24
	Number of logical CPUs: 24
	Graphics card #0 name: Intel(R) Graphics
	Graphics card #0 vendor: Intel Corporation
	Graphics card #0 VRAM (MiB): 2048.00
	Graphics card #0 deviceId: VideoController1
	Graphics card #0 versionInfo: 32.0.101.6881
	Graphics card #1 name: NVIDIA GeForce RTX 5060
	Graphics card #1 vendor: NVIDIA
	Graphics card #1 VRAM (MiB): 8151.00
	Graphics card #1 deviceId: VideoController2
	Graphics card #1 versionInfo: 32.0.15.8097
	Memory slot #0 capacity (MiB): 32768.00
	Memory slot #0 clockSpeed (GHz): 5.60
	Memory slot #0 type: DDR5
	Memory slot #1 capacity (MiB): 32768.00
	Memory slot #1 clockSpeed (GHz): 5.60
	Memory slot #1 type: DDR5
	Virtual memory max (MiB): 69074.75
	Virtual memory used (MiB): 33155.10
	Swap memory total (MiB): 4096.00
	Swap memory used (MiB): 312.32
	Space in storage for jna.tmpdir (MiB): available: 1079715.75, total: 1950438.00
	Space in storage for org.lwjgl.system.SharedLibraryExtractPath (MiB): available: 1079715.75, total: 1950438.00
	Space in storage for io.netty.native.workdir (MiB): available: 1079715.75, total: 1950438.00
	Space in storage for java.io.tmpdir (MiB): available: 1079715.75, total: 1950438.00
	Space in storage for workdir (MiB): available: 1079715.75, total: 1950438.00
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096M
	Debug Flags: 0 total; 
	Fabric Mods: 
		betterpingdisplay: Better Ping Display 1.1.1
		fabric-api: Fabric API 0.136.0+1.21.10
			fabric-api-base: Fabric API Base 1.0.0+14b92d896f
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.106+d17682156f
			fabric-biome-api-v1: Fabric Biome API (v1) 16.1.0+c2417d4f6f
			fabric-block-api-v1: Fabric Block API (v1) 1.1.5+d17682156f
			fabric-block-view-api-v2: Fabric BlockView API (v2) 1.0.34+e4fd1b926f
			fabric-command-api-v2: Fabric Command API (v2) 2.4.0+c0ab2d5d6f
			fabric-content-registries-v0: Fabric Content Registries (v0) 10.2.4+b6a242646f
			fabric-convention-tags-v1: Fabric Convention Tags 2.1.48+7f945d5b6f
			fabric-convention-tags-v2: Fabric Convention Tags (v2) 2.16.0+552403eb6f
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.3.18+33df5e6e6f
			fabric-data-attachment-api-v1: Fabric Data Attachment API (v1) 1.8.30+68e881bd6f
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 23.2.24+d8b85ef16f
			fabric-dimensions-v1: Fabric Dimensions API (v1) 4.0.22+38b9cc196f
			fabric-entity-events-v1: Fabric Entity Events (v1) 2.1.13+fde3702c6f
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 4.0.36+5ba217126f
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.1.1+e47eaae56f
			fabric-item-api-v1: Fabric Item API (v1) 11.5.9+9bce411b6f
			fabric-item-group-api-v1: Fabric Item Group API (v1) 4.2.25+86b3ae576f
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.1.1+b3ba9c486f
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.6.9+33df5e6e6f
			fabric-loot-api-v2: Fabric Loot API (v2) 3.0.65+3f89f5a56f
			fabric-loot-api-v3: Fabric Loot API (v3) 2.0.12+d17682156f
			fabric-message-api-v1: Fabric Message API (v1) 6.1.7+3154c1c86f
			fabric-model-loading-api-v1: Fabric Model Loading API (v1) 6.0.2+3ffd6ef06f
			fabric-networking-api-v1: Fabric Networking API (v1) 5.1.0+b095d8db6f
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 21.1.26+9bce411b6f
			fabric-particles-v1: Fabric Particles (v1) 4.2.3+a0ee59a46f
			fabric-recipe-api-v1: Fabric Recipe API (v1) 8.1.27+d17682156f
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 6.1.42+679c8c5c6f
			fabric-renderer-api-v1: Fabric Renderer API (v1) 7.2.0+3706cdf36f
			fabric-renderer-indigo: Fabric Renderer - Indigo 4.1.1+d7df91576f
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.1.38+86b3ae576f
			fabric-rendering-v1: Fabric Rendering (v1) 16.0.2+19a99b056f
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 5.0.28+33df5e6e6f
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 3.2.3+3388a3b26f
			fabric-resource-loader-v1: Fabric Resource Loader (v1) 1.0.3+8cc86c156f
			fabric-screen-api-v1: Fabric Screen API (v1) 3.1.0+9c82a7986f
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.151+d17682156f
			fabric-serialization-api-v1: Fabric Serialization API (v1) 1.0.0+d857c9766f
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.45+328a75ba6f
			fabric-tag-api-v1: Fabric Tag API (v1) 1.2.11+2fa446b26f
			fabric-transfer-api-v1: Fabric Transfer API (v1) 6.0.15+79ec2c126f
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 6.5.3+41eb43436f
		fabricloader: Fabric Loader 0.17.2
			mixinextras: MixinExtras 0.5.0
		java: OpenJDK 64-Bit Server VM 21
		minecraft: Minecraft 1.21.10
		modmenu: Mod Menu 16.0.0-rc.1
			placeholder-api: Placeholder API 2.8.0+1.21.9
	Launched Version: 1.21.10
	Launcher name: theseus
	Backend library: LWJGL version 3.3.3-snapshot
	Backend API: NVIDIA GeForce RTX 5060/PCIe/SSE2 GL version 3.3.0 NVIDIA 580.97, NVIDIA Corporation
	Window size: 854x480
	GFLW Platform: win32
	Render Extensions: GL_ARB_buffer_storage, GL_KHR_debug, GL_ARB_vertex_attrib_binding, GL_ARB_direct_state_access
	GL debug messages: 
	Is Modded: Definitely; Client brand changed to 'fabric'
	Universe: 400921fb54442d18
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Render Distance: 12/12 chunks
	Resource Packs: vanilla, fabric, betterpingdisplay, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-command-api-v2, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-convention-tags-v2, fabric-crash-report-info-v1, fabric-data-attachment-api-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-loot-api-v3, fabric-message-api-v1, fabric-model-loading-api-v1, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-rendering-fluids-v1, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-resource-loader-v1, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-serialization-api-v1, fabric-sound-api-v1, fabric-tag-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader, modmenu, placeholder-api
	Current Language: ja_jp
	Locale: ja_JP
	System encoding: MS932
	File encoding: UTF-8
	CPU: 24x Intel(R) Core(TM) Ultra 9 285
```
</details>

**Comment by vladmarica** [comment]
Sorry for the delay - official builds of this mods for version 1.21.6 to 1.21.11 are now available on CurseForge and Modrinth.
